---
output: 
  pdf_document:
    latex_engine: xelatex
header-includes: \usepackage {xcolor}
---

\textcolor{white}{.}


\Huge 
{\bf Remerciements}
\vspace{1 cm}


\normalsize
Je souhaite tout d'abord remercier mon professeur Aline Leonet qui m'a aidé à trouver mon stage, ensuite le professeur Philippe Grosjean qui m'a accueilli dans son laboratoire afin d'effectuer ce stage et qui a permis la mise en oeuvre de celui-ci.

Je voudrai également remercier les autres personnes du laboratoire d'Écologie Numérique des Milieux Aquatiques. Tout d'abord, je remercie Guyliann Engels qui m'a suivi de près depuis le début, qui a répondu aux nombreuses questions que je pouvais avoir et qui m'a accueilli dans son bureau. Je remercie Antoine, le technicien capable de maintenir les mésocosmes, il a de nombreuses fois pris le temps de m'aider. 
Je remercie également les mémorants, Madeleine et Rémy pour tous les échanges instructifs que j'ai pu avoir avec eux lors de ce stage. Je remercie aussi Nicolas pour les conseils qu'il m'a prodigués. 

Un dernier remerciement revient à Raphaël qui a créé l'application sur laquelle je me suis inspiré pour commencer la mienne.
\vfill
\null
\newpage
