---
output:
  pdf_document: default
  html_document: default
---


# Communications interpersonnelles 

## Difficultés rencontrées

### R vs python

La principale difficulté rencontrée au début est de passer de l'apprentissage du langage de programmation *python* à *R*. Ce sont tous les deux des langages de programmation interprétés.
*python* a été créé pour faire de la programmation informatique généraliste, il est utilisé dans de larges domaines par des informaticiens. A l'inverse, R est dédié aux analyses statistiques, plutôt utilisées par des spécialistes ou des scientifiques.

Dans le domaine du *data scientist*, *R* et *python* sont courament employé.

### Shiny communication entre ui.R et server.R

Les application web géré par shiny utilise deux fonctions communiquant entre elles **ui** et le **server**

Le schéma de communication basique entre les deux scripts commence par la déclaration d'une variable *inputId = ma_variable* dans ui.R.
Celui-ci est appelé dans server.R sous la forme input$ma_variable, cette variable sera ensuite traitée dans un bloc de code délimiter par des crochets.

Shiny utilise du Javascript pour dynamiser l'interface de l'utilisateur sous une couche de code masqué, cette couche simplifie grandement le travail avec R.
Si on sort du cadre de l'utilisation prévu par Shiny, on se heurte à de grands soucis de codage. Shiny restreint donc, la communication entre les différents blocs de code.
Dans certaines situations cela complique le travail.


### Apport au sein de l'entreprise

Pour l'instant, la contribution à l'entreprise revient principalement aux relevés des boutures (monitoring) et l'encodage, ceci permet de libérer du temps au technicien.
L'application qui est en développement est utilisé dans le travail de mémoire de Madeleine Gilles.



